### PR TITLE
update Zigbee and Bluetooth mesh models

### PR DESCRIPTION
**Pull request by mjkoster**
fix broken pointers

### CODE REVIEW

**Review by cabo — CHANGES_REQUESTED** [review]
You didn't merge/rebase on master, so the new CI isn't in.

I still see:

```
./sdfObject/sdfobject-genericdefaulttransitiontime.sdf.json (Bluetooth SIG, Inc.):
- #/sdfObject/GenericDefaultTransitionTime/sdfAction/>>LevelSet<</sdfData/Level
- #/sdfObject/GenericDefaultTransitionTime/sdfAction/>>LevelSet<</sdfData/TransitionTime
- #/sdfObject/GenericDefaultTransitionTime/sdfAction/>>LevelSet<</sdfData/Delay
```

**Comment by mjkoster** [comment]
I fixed the pointers. Do I need to do anything else for the CI problem, or can we merge?

**Comment by cabo** [comment]
Not quite:

```
./sdfObject/sdfobject-genericdefaulttransitiontime.sdf.json (Bluetooth SIG, Inc.):
- #/sdfObject/GenericDefaultTransitionTime/sdfAction/DefaultTransitionTimeGet/sdfData/>>Level<<
- #/sdfObject/GenericDefaultTransitionTime/sdfAction/DefaultTransitionTimeGet/sdfData/>>TransitionTime<<
- #/sdfObject/GenericDefaultTransitionTime/sdfAction/DefaultTransitionTimeGet/sdfData/>>Delay<<
```

**Comment by mjkoster** [comment]
I can make a new branch off master and drop the changed files there, or do I somehow re-base an existing branch?

**Comment by mjkoster** [comment]
Pushed another update

**Comment by cabo** [comment]
OK, I hope that will run through the real CI now -- I didn't see anything that remained broken, but with 838 other errors that was hard to examine.

**Pull request merged**
