### PR TITLE
fix ZCL examples

### PR DESCRIPTION
**Pull request by mjkoster**
update typos and omissions

### CODE REVIEW

**Comment by mjkoster** [comment]
I fixed the omissions and typos, and replicated the bitmap pattern we agreed on. Also used "oneOf" to define the case where special values of a number range have special meaning.

**Comment by cabo** [comment]
```
** Features potentially used: allowed-ext: [{"ExecuteIfOff"=>false, "CoupleColorTempToLevel"=>false}], data-ext: ["oneOf"], top-ext: ["defaultnamespace"]
sdfObject/sdfobject-level.sdf.json
```
So this still has a typo in defaultNamespace [sic!], uses oneOf (which really nobody should ever use), and uses an incompatible default in "Options".

I have a larger problem with onoff, which I'm still hunting for.

**Comment by cabo** [comment]
Ah, you fixed onoff in the meantime.

**Comment by cabo** [comment]
** Features potentially used: allowed-ext: [{"ExecuteIfOff"=>false, "CoupleColorTempToLevel"=>false}], data-ext: ["anyOf"]

(We didn't even put in anyOf, which we probably will at some point.)
And the Options default = (object) remains...

**Comment by mjkoster** [comment]
fixed the issue with default "Options" property and I think I'm using "anyOf" correctly (to model the special value cases of startup settings)

**Comment by mjkoster** [comment]
We had the discussion and decided to not use oneOf, which I thought was a decision to include anyOf 

So now we have an example pattern using anyOf to show how it is useful. We could include it as our first feature addition

Maybe we can fix it as an omission in v1

**Comment by cabo** [comment]
I find this pattern intriguing.  You use choice (anyOf) to give the two extreme values of a contiguous scale special semantics (0/1..254/255), but, structurally, this is just 0..255, and within SDF 1.0 means could be described as such.

Certainly, v1.1 will have more data description functionality.  Trying this out would be for the experimental repo, while this repo could use the simple 0..255 description for now.

**Comment by mjkoster** [comment]
There is a need to describe the special values semantically. For the meantime, I defined the value as 1-254 and a separate property for the 0,255 enum. Right now SDF has a huge gap in not being able to provide semantic anchors for enumerated values, and this is probably a special case of that huge gap. I think we need to prioritize sdfEnum and add it ASAP.

**Comment by cabo** [comment]
That now certainly validates.  I'm not sure I would have introduced a separate property "StartUpCurrentLevelSpecialValues"; I simply would have had "StartUpCurrentLevel" include 0 and 255 and put the special semantics in the description.

Yes, we need to be able to annotate specific values with semantics.  I'm not sure that "Enum" is always the right way to do this; if you have a continuous scale and want to mark certain values on that (e.g., geometric mid-point), Enum doesn't fit.
It is convenient to be able to write the semantic annotation with the Enum values if it is an actual Enum (which is just a specific kind of choice, redundant with anyOf, if we really need that).

**Comment by mjkoster** [comment]
I think about the modeling of this pattern in the way I modeled it. There is a 2-way choice between a scalar value setting and a behavioral setting. The behavioral setting further has a 2-way choice. A setter application is going to choose from essentially 3 options, a lowest possible value, a preset value, and a stored value. I suggest that it has the underlying pattern of both an enum and a scalar. Sure, it's a crap pattern, but how can we model it in a way that makes sense to an application. The fact that they chose to overload a single octet seems like something we should try to keep separate from the semantics somehow. 

You recommend that for now we only represent the bit field as a scalar in the machine readable form, which I am sure will not be something I want to show my ZCL colleagues. Yes, we have a "Zigbee" model in the PG but the ZCL people will reject it because it doesn't have the descriptive power today. I will need to make a speculative version in the experimental repo for the ZCL conversation.

**Comment by WAvdBeek** [comment]
is it possible to use the copyright of Zigbee, since it is an Zigbee donated model under the BSD-3 license?
if done, can we please merge this pull request? so that we have a Zigbee model in the playground
what about the BLE models?

**Comment by mjkoster** [comment]
I am discussing the BLE model with Szymon. I would like for now to include the sdfObject level only and leave out the sdfThing (combined device) that Szymon is asking about.

**Comment by WAvdBeek** [comment]
I agree, the thing level is right now not important.

**Comment by mjkoster** [comment]
OK back to the attribute with special values, here is what the ZCL XML for that definition looks like:
```
      <attribute id="4000" name="StartUpCurrentLevel" type="uint8" max="255" writable="true">
        <restriction>
          <type:special value="00" name="MinimumDeviceValuePermitted" />
          <type:enumeratedRange min="01" max="fe" />
          <type:special value="ff" name="SetToPreviousValue" />
        </restriction>
      </attribute>
```
They describe the range of the attribute, and use the "restriction" element to declare "special" and "enumeratedRange" as types. So it's sort of like the multiple choice pattern I discussed earlier but I think we can do much better in terms of simplifying.

**Comment by mjkoster** [comment]
Also on the enum subject:
```  <type:type short="LevelOptions" name="LevelOptions" id="18" inheritsFrom="map8">
    <bitmap>
      <element name="ExecuteIfOff" type="bool" mask="01" />
      <!-- Used in Level Control for Lighting -->
      <element name="CoupleColorTempToLevel" type="bool" mask="02" shiftRight="1" />
    </bitmap>
  </type:type>
  <type:type short="MoveStepMode" name="MoveStepMode" id="30" inheritsFrom="enum8">
    <restriction>
      <type:enumeration value="00" name="Up" />
      <type:enumeration value="01" name="Down" />
    </restriction>
  </type:type>
```
For LevelOptions we decided on Array type with uniqueItems to model bitmaps, so that works out OK

But for MoveStepMode, I currently have:
```
"enum": [0,1] 
```
but it could also be 
```
"enum": [{"Up": 0},{"Down": 1}] 
```
or if we use a machine conversion it might convert to 
```
"enum": [{"name":"Up", "value":"00"}, {"name":"Down", "value":"01"}] 
```
which wouldn't validate instances...

**Comment by cabo** [comment]
I think there are several aspects here:

-- properties with several discrete, named states.

-- arrays of these states, sets of states == arrays of bits, one for each state

So we want to be able to give these names such as up and down -- we can do that today.
We also want to be able to give them numeric values, so we can use them as array indexes (including indexes into a bitmap).
Are those numeric values essential for the model or are they binding information?

Do we have a way to attach semantic information to the names?  (Of course, the names themselves could be pointed to, but can we point from the names to semantic information?)

**Comment by WAvdBeek** [comment]
we can use the names, since we want the semantic description, the numerical values on the wire are nice to capture, but i see that as a serialization.

**Comment by mjkoster** [comment]
I include just the string values for now; maybe we can think about a mapping file approach to assign numbers or, better still,  we can fix the enum pattern to enable better semantic anchors

**Comment by mjkoster** [comment]
RTM? When we merge this we should squash...

**Comment by cabo** [comment]
It is a bit hard to review on github because it shows the differences to pre-#39 master.
It continues to validate.

I'm not quite sure about the array with unique Booleans in OnWithTimedOff (which can only be [], [false], [true], [false, true] or [true, false], what?); all of the elements are described as "Accept Only When On" -- what does that mean?

**Comment by mjkoster** [comment]
It's a bitmap with one element. I corrected it to be an array with one boolean. I also added a couple of command parameters that were missing from the earlier ZCL I converted from.

**Comment by mjkoster** [comment]
And now the validation syntax doesn't recognize the array form of array constraint, where each item is described in sequence. It seems like this makes sense for a bitmap. Is there a good reason for not allowing it? 
```
            "OnOffControl": {
              "description": "implemented as a bitmap, modeled as an array of boolean",
              "type": "array",
              "maxItems": 1,
              "items" : [
                {
                  "type": "boolean",
                  "description": "Accept Only When On"
                }
              ]
            }
```

**Comment by mjkoster** [comment]
Switched this bitmap to use the unique string enum as we did in the level model. 
```
            "OnOffControl": {
              "description": "implemented as a bitmap, modeled as an array of unique string items",
              "type": "array",
              "uniqueItems": true,
              "items" : {
                "type": "string",
                "enum": [ "AcceptOnlyWhenOn" ]
              }
            },
```
The mapping file gets interesting but I think can be done with a bitmask entry instead of an ID entry.
```
"#/sdfObject/OnOff/sdfAction/OnWithTimedOff": { "id": 42 }
"#/sdfObject/OnOff/sdfAction/OnWithTimedOff/sdfData/OnOffControl/items/enum/0": { "bitmask": 1 }
```

**Comment by cabo** [comment]
Looks good.

The weird thing is that the positioning in the enum array now gets semantics -- via the JSON pointer.
Didn't think about that yet; I'm afraid that additional interfacing surface of the spec will create brittleness.

Anyway, this is now good enough.  Merging it...

**Pull request merged**
